logging.config=config/logback-local.xml
server.port=8081

spring.cloud.aws.credentials.profile-name=default
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

aws.region-code=us-east-1
aws.profile-name=default
aws.endpoint-url=http://localhost:4566

#Dynamo Db
fantawin.dao.players-table-name=Players
fantawin.dao.player-match-stats-table-name=PlayerMatchStats
fantawin.dao.fixtures-table-name=Fixtures
fantawin.dao.availability-reports-table-name=AvailabilityReports
fantawin.dao.roster-table-name=Roster