logging.config=config/logback-local.xml
server.port=8081
middleware.init.aws=true
spring.cloud.aws.credentials.profile-name=default
spring.cloud.aws.region.static=us-east-1
spring.cloud.aws.endpoint=http://localhost:4566

aws.region-code=us-east-1
aws.profile-name=default
aws.endpoint-url=http://localhost:4566


fantawin.default-match-difficulty=5.0
fantawin.big-player-threshold=6.5

#Dynamo Db
fantawin.dao.players-table-name=Players
fantawin.dao.player-match-stats-table-name=PlayerMatchStats
fantawin.dao.fixtures-table-name=Fixtures
fantawin.dao.availability-reports-table-name=AvailabilityReports
fantawin.dao.roster-table-name=Roster

#external client
fantawin.football-data-base-url=https://api.football-data.org/v4

# DA VERIFICARE con GET /competitions/SA/teams -> teamIds
football-data.team-ids.Inter=
football-data.team-ids.Milan=
football-data.team-ids.Juventus=
football-data.team-ids.Napoli=


fantawin.rest-template.retry-max-attempts=3
fantawin.rest-template.connection-timeout=5000
fantawin.rest-template.read-timeout=10000
pn.log.trace-id-header=x-trace-id